name: CI model to docker hub 

#trigger
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

  # accion (cual es la acccion que queremos que haga)
jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t magoher/obesity-detection:v1 .

      - name: Docker push to dockerhub
        run: docker push magoher/obesity-detection:v1
